<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: /app/src/views/class.latte */
final class Template_f542ed440f extends Latte\Runtime\Template
{
	public const Source = '/app/src/views/class.latte';

	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		$this->renderBlock('content', get_defined_vars()) /* line 3 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['template' => '27', 'interface' => '60', 'constant' => '72', 'key' => '92', 'item' => '92', 'property' => '123', 'method' => '153', 'parameter' => '177'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = 'layout.latte';
		return get_defined_vars();
	}


	/** {block content} on line 3 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<main class="structure">
  <div class="basic-info">
    <div class="namespace">
      namespace <b>';
		echo LR\Filters::escapeHtmlText($class->namespace) /* line 7 */;
		echo '</b>
    </div>
    <div class="declaration">
      <span class="modifiers">
';
		if ($class->isFinal) /* line 11 */ {
			echo '          final
';
		}
		if ($class->isAbstract) /* line 14 */ {
			echo '          abstract
';
		}
		if ($class->isReadOnly) /* line 17 */ {
			echo '          readonly
';
		}
		echo '        class
      </span>
      <span class="structure-name">
        ';
		echo $class->basename /* line 23 */;
		echo "\n";
		if ($class->templates !== []) /* line 24 */ {
			echo '        <span class="generics">
          <span class="brace">&lt;</span>
';
			foreach ($iterator = $ʟ_it = new Latte\Essential\CachingIterator($class->templates, $ʟ_it ?? null) as $template) /* line 27 */ {
				echo '            <span class="generic">
              <span class="template-name">';
				echo LR\Filters::escapeHtmlText($template->name) /* line 30 */;
				echo '</span>
';
				if ($template->bound instanceof Kirameki\ApiDocGenerator\Types\VarType) /* line 31 */ {
					echo '                <span class="bound-delimiter"> as </span>
                <span class="bound">
';
					$this->createTemplate('type.latte', ['type' => $template->bound] + $this->params, 'include')->renderToContentType('html') /* line 34 */;
					echo '                </span>
';
				}
				echo '            </span>
';
				if (!$iterator->isLast()) /* line 38 */ {
					echo '            <span class="delimiter">,</span>';
				}
				echo "\n";

			}
			$iterator = $ʟ_it = $ʟ_it->getParent();

			echo '          <span class="brace">&gt;</span>
';
		}
		echo '      </span>
    </div>
  </div>
  <div class="details">
';
		if ($class->parent !== null) /* line 46 */ {
			echo '    <div class="extends">
      extends:
      <ul>
        <li>
';
			$this->createTemplate('type.latte', ['type' => $class->parent] + $this->params, 'include')->renderToContentType('html') /* line 51 */;
			echo '        </li>
      </ul>
    </div>
';
		}
		if ($class->interfaces !== []) /* line 56 */ {
			echo '    <div class="implements">
      implements:
      <ul>
';
			foreach ($class->interfaces as $interface) /* line 60 */ {
				echo '          <li>
';
				$this->createTemplate('type.latte', ['type' => $interface] + $this->params, 'include')->renderToContentType('html') /* line 62 */;
				echo '          </li>
';

			}

			echo '      </ul>
    </div>
';
		}
		if ($class->constants !== []) /* line 68 */ {
			echo '      <div class="constants">
        <h3>Constants</h3>
        <ul>
';
			foreach ($class->constants as $constant) /* line 72 */ {
				echo '            <li>
              <div class="constant-signature">
                <span class="modifiers">
';
				if ($constant->isFinal) /* line 77 */ {
					echo '                    final
';
				}
				echo '                  ';
				echo LR\Filters::escapeHtmlText($constant->visibility->value) /* line 80 */;
				echo '
                </span>
                <span class="type">';
				echo LR\Filters::escapeHtmlText($constant->type) /* line 82 */;
				echo '</span>
                <span class="name">';
				echo LR\Filters::escapeHtmlText($constant->name) /* line 83 */;
				echo '</span>
                <span class="assignment"> = </span>
';
				$value = $constant->value /* line 85 */;
				if ($value instanceof \UnitEnum) /* line 86 */ {
					echo '                  <span class="value value-enum">';
					echo LR\Filters::escapeHtmlText($value::class) /* line 87 */;
					echo '::';
					echo LR\Filters::escapeHtmlText($value->name) /* line 87 */;
					echo '</span>
';
				} elseif (is_array($value)) /* line 88 */ {
					echo '                  <div class="value value-array">
                    [
                    <ul>
';
					foreach ($value as $key => $item) /* line 92 */ {
						echo '                        <li>
';
						if (is_string($key)) /* line 94 */ {
							echo '                            "<span class="array-key-string">';
							echo LR\Filters::escapeHtmlText($key) /* line 95 */;
							echo '</span>" =>
';
						} else /* line 96 */ {
							echo '                            <span class="array-key-int">';
							echo LR\Filters::escapeHtmlText($key) /* line 97 */;
							echo '</span> =>
';
						}
						if (is_string($item)) /* line 99 */ {
							echo '                            <span class="value value-string">"';
							echo LR\Filters::escapeHtmlText($value) /* line 100 */;
							echo '"</span>
';
						} else /* line 101 */ {
							echo '                            <span class="array-value-default">';
							echo LR\Filters::escapeHtmlText($item) /* line 102 */;
							echo '</span>
';
						}
						echo '                        </li>
';

					}

					echo '                    ]
                  </div>
';
				} elseif (is_string($value)) /* line 108 */ {
					echo '                  <span class="value value-string">"';
					echo LR\Filters::escapeHtmlText($value) /* line 109 */;
					echo '"</span>
';
				} else /* line 110 */ {
					echo '                  <span class="value value-default">';
					echo LR\Filters::escapeHtmlText($value) /* line 111 */;
					echo '</span>
';
				}


				echo '              </div>
            </li>
';

			}

			echo '        </ul>
      </div>
';
		}
		if ($class->properties !== []) /* line 119 */ {
			echo '      <div class="properties">
        <h3>Properties</h3>
        <ul>
';
			foreach ($class->properties as $property) /* line 123 */ {
				echo '            <li>
              <div class="signature">
                <span class="modifiers">
';
				if ($property->isReadOnly) /* line 128 */ {
					echo '                    readonly
';
				}
				if ($property->isStatic) /* line 131 */ {
					echo '                    static
';
				}
				echo '                  ';
				echo LR\Filters::escapeHtmlText($property->visibility->value) /* line 134 */;
				echo '
                </span>
                <span class="var-type">
';
				$this->createTemplate('type.latte', ['type' => $property->type] + $this->params, 'include')->renderToContentType('html') /* line 137 */;
				echo '                </span>
                <span class="var-name">$';
				echo LR\Filters::escapeHtmlText($property->name) /* line 139 */;
				echo '</span>
              </div>
              <div class="comment">
                ';
				echo $property->commentAsMarkdown() /* line 142 */;
				echo '
              </div>
            </li>
';

			}

			echo '        </ul>
      </div>
';
		}
		if ($class->methods !== []) /* line 149 */ {
			echo '      <div class="methods-wrapper">
        <h3>Methods</h3>
        <ul class="methods">
';
			foreach ($class->methods as $method) /* line 153 */ {
				echo '            <li class="method">
              <a id="';
				echo LR\Filters::escapeHtmlAttr($method->id) /* line 156 */;
				echo '" class="anchor" href="';
				echo LR\Filters::escapeHtmlAttr(LR\Filters::safeUrl($class->outputPath)) /* line 156 */;
				echo '#';
				echo LR\Filters::escapeHtmlAttr($method->id) /* line 156 */;
				echo '">
                <i class="fa-solid fa-link"></i>
              </a>
              <div class="signature">
                <span class="modifiers">
';
				if ($method->isFinal) /* line 161 */ {
					echo '                    final
';
				}
				echo '                  ';
				echo LR\Filters::escapeHtmlText($method->visibility->value) /* line 164 */;
				echo "\n";
				if ($method->isStatic) /* line 165 */ {
					echo '                    static
';
				}
				if ($method->isAbstract) /* line 168 */ {
					echo '                    abstract
';
				}
				echo '                  function
                </span>
                <span class="name">
';
				if ($method->parameters !== []) /* line 174 */ {
					echo '                  <span class="method-name-start">';
					echo LR\Filters::escapeHtmlText($method->name) /* line 175 */;
					echo '(</span>
                  <ul class="parameters">
';
					foreach ($method->parameters as $parameter) /* line 177 */ {
						echo '                      <li class="parameter">
';
						if ($parameter->isPassedByReference) /* line 180 */ {
							echo '                          &
';
						}
						if ($parameter->isVariadic) /* line 183 */ {
							echo '                          ...
';
						}
						if ($parameter->type !== null) /* line 186 */ {
							echo '                          <span class="types">
';
							$this->createTemplate('type.latte', ['type' => $parameter->type] + $this->params, 'include')->renderToContentType('html') /* line 188 */;
							echo '                          </span>
';
						}
						echo '                        <var>$';
						echo LR\Filters::escapeHtmlText($parameter->name) /* line 191 */;
						echo '</var>
                        <span class="default-set">
';
						if ($parameter->hasDefault) /* line 193 */ {
							echo '                            <span class="assignment">=</span>
';
							if ($parameter->defaultConstant) /* line 195 */ {
								echo '                              <span class="value value-constant">';
								echo LR\Filters::escapeHtmlText($parameter->defaultConstant) /* line 196 */;
								echo '</span>
';
							} else /* line 197 */ {
								$defaultValue = $parameter->defaultValue /* line 198 */;
								if (is_string($defaultValue)) /* line 199 */ {
									echo '                                <span class="value value-string">"';
									echo LR\Filters::escapeHtmlText($defaultValue) /* line 200 */;
									echo '"</span>
';
								} elseif (is_array($defaultValue)) /* line 201 */ {
									echo '                                <span class="value value-array">[...]</span>
';
								} elseif ($defaultValue === null) /* line 203 */ {
									echo '                                <span class="value value-null">null</span>
';
								} elseif (is_bool($defaultValue)) /* line 205 */ {
									echo '                                <span class="value value-bool">';
									echo LR\Filters::escapeHtmlText($defaultValue ? 'true' : 'false') /* line 206 */;
									echo '</span>
';
								} else /* line 207 */ {
									echo '                                <span class="value value-default">';
									echo LR\Filters::escapeHtmlText($defaultValue) /* line 208 */;
									echo '</span>
';
								}



							}
						}
						echo '                        </span>
                        <span class="delimiter">,</span>
                      </li>
';

					}

					echo '                  </ul>
                  <span class="method-name-end">):</span>
';
				} else /* line 218 */ {
					echo '                    ';
					echo LR\Filters::escapeHtmlText($method->name) /* line 219 */;
					echo '():
';
				}
				echo '                <span class="return">
';
				$this->createTemplate('type.latte', ['type' => $method->returnType] + $this->params, 'include')->renderToContentType('html') /* line 222 */;
				echo '                </span>
              </div>
              <div class="comment">
                ';
				echo $method->commentAsMarkdown() /* line 226 */;
				echo '
              </div>
            </li>
';

			}

			echo '        </ul>
      </div>
';
		}
		echo '  </div>
</main>
';
	}
}
